import type { DocumentRecord } from '../types.js';

export function renderDocumentsMd(docs: DocumentRecord[]): string {
  const rows = [...docs].sort((a, b) =>
    a.date === b.date ? a.id.localeCompare(b.id) : a.date.localeCompare(b.date));

  const head = `# Magisterial Documents

Generated by \`npm run render\` from \`data/documents/*.json\` — do not edit by hand.

Identifiers follow \`mag:{issuer}/{incipit-slug}-{year}\`; the issuer segment is always the local
part of \`issuerId\`, so conciliar documents namespace under their council and record the
promulgating pope separately. See the design spec for the minting rules.

${rows.length} documents.

| ID | Incipit | Genre | Issuer | Date | Promulgated by |
| --- | --- | --- | --- | --- | --- |`;

  const body = rows.map((d) =>
    `| \`${d.id}\` | ${d.title} | ${d.genre ?? `— (${d.sourceGenreLabel ?? 'unmapped'})`} `
    + `| \`${d.issuerId}\` | ${d.date} | ${d.promulgatedBy ? `\`${d.promulgatedBy}\`` : ''} |`);

  return `${head}\n${body.join('\n')}\n`;
}
