import { cell, byDateThenId, idCell, FOOTNOTE } from './table.js';
import type { DocumentRecord } from '../types.js';

export function renderGenreMd(genreId: string | null, docs: DocumentRecord[]): string {
  const rows = [...docs].sort(byDateThenId);
  const heading = genreId === null
    ? 'Documents with an unmapped genre'
    : `Documents of genre \`${genreId}\``;
  const preamble = genreId === null
    ? '\nThe source genre has no Genre Registry row yet; the raw label is preserved in the '
      + 'Source label column rather than a taxonomy being invented for it. See the design spec §2.6.\n'
    : '';

  const head = `# ${heading}

Generated by \`npm run render\` from \`data/documents/*.json\` — do not edit by hand.
${preamble}
${rows.length} documents.

| ID | Title | Incipit | Issuer | Date | Promulgated by |${genreId === null ? ' Source label |' : ''}
| --- | --- | --- | --- | --- | --- |${genreId === null ? ' --- |' : ''}`;

  const body = rows.map((d) =>
    `| ${idCell(d)} | ${cell(d.title)} | ${d.incipit ? cell(d.incipit) : ''} `
    + `| \`${d.issuerId}\` | ${d.date} | ${d.promulgatedBy ? `\`${d.promulgatedBy}\`` : ''} |`
    + (genreId === null ? ` ${cell(d.sourceGenreLabel ?? '')} |` : ''));

  return `${head}\n${body.join('\n')}\n\n${FOOTNOTE}\n`;
}
