import { POPES } from '../mappings/index.js';
import { issuerLocalPart } from '../ids.js';
import type { DocumentRecord } from '../types.js';

const group = <K>(docs: DocumentRecord[], key: (d: DocumentRecord) => K): Map<K, DocumentRecord[]> => {
  const out = new Map<K, DocumentRecord[]>();
  for (const d of docs) out.set(key(d), [...(out.get(key(d)) ?? []), d]);
  return out;
};

const range = (docs: DocumentRecord[]): string => {
  const dates = docs.map((d) => d.date).sort();
  return dates.length === 0 ? '' : `${dates[0]} – ${dates[dates.length - 1]}`;
};

/** The genre view's filename; a null genre files under `unmapped`. */
export const genreFile = (genre: string | null): string => genre ?? 'unmapped';

export function renderIndexMd(docs: DocumentRecord[]): string {
  const byIssuer = [...group(docs, (d) => d.issuerId)].sort(
    (a, b) => range(a[1]).localeCompare(range(b[1])));
  const byGenre = [...group(docs, (d) => d.genre)].sort(
    (a, b) => genreFile(a[0]).localeCompare(genreFile(b[0])));
  const provisional = docs.filter((d) => d.idStatus === 'provisional').length;

  const shelvesOf = (issuerId: string): string => {
    const pope = POPES.find((p) => p.issuerId === issuerId);
    if (!pope) return '— (conciliar)';
    return pope.era === 'flat' ? 'whole-pontificate index' : pope.shelves.join(', ');
  };

  const issuerRows = byIssuer.map(([issuerId, ds]) => {
    const local = issuerLocalPart(issuerId);
    return `| [\`${issuerId}\`](documents/by-issuer/${local}.md) | ${ds.length} `
      + `| ${range(ds)} | ${shelvesOf(issuerId)} |`;
  });

  const genreRows = byGenre.map(([genre, ds]) =>
    `| [\`${genre ?? 'unmapped'}\`](documents/by-genre/${genreFile(genre)}.md) `
    + `| ${ds.length} | ${range(ds)} |`);

  return `# Magisterial Documents

Generated by \`npm run render\` from \`data/documents/*.json\` — do not edit by hand.

Identifiers follow \`mag:{issuer}/{incipit-slug}-{year}\`; the issuer segment is always the local
part of \`issuerId\`, so conciliar documents namespace under their council and record the
promulgating pope separately. See the design spec for the minting rules.

**${docs.length} documents**, of which ${provisional} carry a provisional identifier — the source
prints no incipit for them, so their id is genre-and-date based and may be re-minted.

Every document appears in both views below; neither is a subset of the other.

## By issuer

| Issuer | Documents | Dates | Shelves harvested |
| --- | --- | --- | --- |
${issuerRows.join('\n')}

## By genre

| Genre | Documents | Dates |
| --- | --- | --- |
${genreRows.join('\n')}

## Coverage

This registry covers the **formal document shelves** of vatican.va. Deliberately absent:

- **Occasional acts** — speeches (after Leo XIII, whose are genuine Latin allocutions), homilies,
  general audiences, Angelus addresses, messages, prayers, travels and *cotidie*. They are roughly
  99% of the archive by volume and need an identifier rule for documents whose heading is a bare
  date, which this registry does not yet have.
- **Year-partitioned \`letters\` shelves** — Benedict XV, and Paul VI onward. The \`letters\` shelf is
  harvested only where the aggregate index carries its items.
- **Bishops' conferences and dicasterial documents**, which remain outside the repository's scope.

The Shelves harvested column above is generated from the harvest configuration itself, so it cannot
drift from what was actually read.
`;
}
