import { POPES, isUnconfirmedCandidate } from '../mappings/index.js';
import { issuerLocalPart } from '../ids.js';
import type { DocumentRecord } from '../types.js';

const group = <K>(docs: DocumentRecord[], key: (d: DocumentRecord) => K): Map<K, DocumentRecord[]> => {
  const out = new Map<K, DocumentRecord[]>();
  for (const d of docs) out.set(key(d), [...(out.get(key(d)) ?? []), d]);
  return out;
};

const range = (docs: DocumentRecord[]): string => {
  const dates = docs.map((d) => d.date).sort();
  return dates.length === 0 ? '' : `${dates[0]} – ${dates[dates.length - 1]}`;
};

/** The genre view's filename; a null genre files under `unmapped`. */
export const genreFile = (genre: string | null): string => genre ?? 'unmapped';

// Codepoint order, not locale collation -- see harvest/ordinals.ts for why: these sorts
// determine the byte order of the checked-in registry/documents.md file, so they must be
// identical on every machine and CI runner regardless of ICU data or LANG.
const cmp = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

export function renderIndexMd(docs: DocumentRecord[]): string {
  // Grouped by the same key run.ts uses to name the file (issuerLocalPart), not the full
  // issuerId, so a row's count and date range can never diverge from the file it links to.
  const byIssuer = [...group(docs, (d) => issuerLocalPart(d.issuerId))].sort(
    (a, b) => cmp(range(a[1]), range(b[1])));
  const byGenre = [...group(docs, (d) => d.genre)].sort(
    (a, b) => cmp(genreFile(a[0]), genreFile(b[0])));
  const byKeyword = new Map<string, DocumentRecord[]>();
  for (const d of docs) {
    for (const k of d.keywords ?? []) byKeyword.set(k, [...(byKeyword.get(k) ?? []), d]);
  }
  const provisional = docs.filter((d) => d.idStatus === 'provisional').length;
  const candidates = docs.filter(isUnconfirmedCandidate).length;

  const shelvesOf = (issuerId: string): string => {
    const pope = POPES.find((p) => p.issuerId === issuerId);
    if (!pope) return '— (conciliar)';
    return pope.era === 'flat' ? 'whole-pontificate index' : pope.shelves.join(', ');
  };

  const issuerRows = byIssuer.map(([local, ds]) => {
    // The local part is shared by construction; the full issuerId(s) that produced it are
    // read back off the documents themselves rather than assumed from a prefix.
    const issuerIds = [...new Set(ds.map((d) => d.issuerId))].sort();
    const label = issuerIds.map((id) => `\`${id}\``).join(', ');
    const shelves = issuerIds.map(shelvesOf).join('; ');
    return `| [${label}](documents/by-issuer/${local}.md) | ${ds.length} `
      + `| ${range(ds)} | ${shelves} |`;
  });

  const genreRows = byGenre.map(([genre, ds]) =>
    `| [\`${genre ?? 'unmapped'}\`](documents/by-genre/${genreFile(genre)}.md) `
    + `| ${ds.length} | ${range(ds)} |`);

  const keywordSection = byKeyword.size === 0 ? '' : `
## By keyword

A keyword is a descriptive subject tag and carries no claim about authority.

| Keyword | Documents |
| --- | --- |
${[...byKeyword].sort(([a], [b]) => cmp(a, b)).map(([k, ds]) =>
    `| [\`${k}\`](documents/by-keyword/${k}.md) | ${ds.length} |`).join('\n')}
`;

  const provisionalLine = provisional === 0
    ? `**${docs.length} documents**, none of which carry a provisional identifier.`
    : `**${docs.length} documents**, of which ${provisional} carry a provisional identifier — `
      + 'the source prints no incipit for them, so their id is genre-and-date based and may '
      + 'be re-minted.';

  return `# Magisterial Documents

Generated by \`npm run render\` from \`data/documents/*.json\` — do not edit by hand.

Identifiers follow \`mag:{issuer}/{incipit-slug}-{year}\`; the issuer segment is always the local
part of \`issuerId\`, so conciliar documents namespace under their council and record the
promulgating pope separately. See the design spec for the minting rules.

${provisionalLine}

Every document appears in both views below; neither is a subset of the other.

## By issuer

| Issuer | Documents | Dates | Shelves harvested |
| --- | --- | --- | --- |
${issuerRows.join('\n')}

## By genre

| Genre | Documents | Dates |
| --- | --- | --- |
${genreRows.join('\n')}
${keywordSection}
## Coverage

This registry covers the **formal document shelves** of vatican.va. Deliberately absent:

- **Occasional acts** — speeches (after Leo XIII, whose are genuine Latin allocutions), homilies,
  general audiences, Angelus addresses, messages, prayers, travels and *cotidie*. They are roughly
  99% of the archive by volume and need an identifier rule for documents whose heading is a bare
  date, which this registry does not yet have.
- **Year-partitioned \`letters\` shelves** — Benedict XV, and Paul VI onward. The \`letters\` shelf is
  harvested only where the aggregate index carries its items.
- **Bishops' conferences and dicasterial documents**, which remain outside the repository's scope.
- **Keyword curation is incomplete.** ${candidates} apostolic constitutions have not yet been confirmed
  as circumscription erections. Their headings print a bare Latin toponym with no marker, so each
  is confirmed by hand against the document's own text.

The Shelves harvested column above is generated from the harvest configuration itself, so it cannot
drift from what was actually read.
`;
}
