import { POPES, isUnconfirmedCandidate } from '../mappings/index.js';
import { isActaShelf } from '../acta/create.js';
import { issuerLocalPart } from '../ids.js';
import type { DocumentRecord } from '../types.js';

const group = <K>(docs: DocumentRecord[], key: (d: DocumentRecord) => K): Map<K, DocumentRecord[]> => {
  const out = new Map<K, DocumentRecord[]>();
  for (const d of docs) out.set(key(d), [...(out.get(key(d)) ?? []), d]);
  return out;
};

const range = (docs: DocumentRecord[]): string => {
  const dates = docs.map((d) => d.date).sort();
  return dates.length === 0 ? '' : `${dates[0]} – ${dates[dates.length - 1]}`;
};

/** The genre view's filename; a null genre files under `unmapped`. */
export const genreFile = (genre: string | null): string => genre ?? 'unmapped';

// Codepoint order, not locale collation -- see harvest/ordinals.ts for why: these sorts
// determine the byte order of the checked-in registry/documents.md file, so they must be
// identical on every machine and CI runner regardless of ICU data or LANG.
const cmp = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

export function renderIndexMd(docs: DocumentRecord[]): string {
  // Grouped by the same key run.ts uses to name the file (issuerLocalPart), not the full
  // issuerId, so a row's count and date range can never diverge from the file it links to.
  // Tie-broken on the issuer key itself (review finding, 2026-09-08): two issuers with
  // identical date ranges would otherwise fall back to Map/group insertion order, which is
  // readdirSync order -- filesystem-dependent, in a file this project checks in.
  const byIssuer = [...group(docs, (d) => issuerLocalPart(d.issuerId))].sort(
    (a, b) => cmp(range(a[1]), range(b[1])) || cmp(a[0], b[0]));
  const byGenre = [...group(docs, (d) => d.genre)].sort(
    (a, b) => cmp(genreFile(a[0]), genreFile(b[0])));
  const byKeyword = new Map<string, DocumentRecord[]>();
  for (const d of docs) {
    for (const k of d.keywords ?? []) byKeyword.set(k, [...(byKeyword.get(k) ?? []), d]);
  }
  const provisional = docs.filter((d) => d.idStatus === 'provisional').length;
  const candidates = docs.filter(isUnconfirmedCandidate).length;

  const shelvesOf = (issuerId: string): string => {
    const pope = POPES.find((p) => p.issuerId === issuerId);
    if (!pope) return '— (conciliar)';
    return pope.era === 'flat' ? 'whole-pontificate index' : pope.shelves.join(', ');
  };
  // The second source, read off the documents themselves: an issuer with documents created
  // from the AAS index (source.shelf `aas/{year}`) says so beside his shelves, with the
  // count and the volume years, so the column cannot drift from the data.
  const actaSourceOf = (ds: DocumentRecord[]): string => {
    const born = ds.filter((d) => isActaShelf(d.source?.shelf));
    if (born.length === 0) return '';
    const years = [...new Set(born.map((d) => d.source!.shelf!.slice('aas/'.length)))].sort();
    return `; AAS index ${years[0]}–${years[years.length - 1]} (${born.length} AAS-only)`;
  };

  const issuerRows = byIssuer.map(([local, ds]) => {
    // The local part is shared by construction; the full issuerId(s) that produced it are
    // read back off the documents themselves rather than assumed from a prefix.
    const issuerIds = [...new Set(ds.map((d) => d.issuerId))].sort();
    const label = issuerIds.map((id) => `\`${id}\``).join(', ');
    const shelves = issuerIds.map(shelvesOf).join('; ') + actaSourceOf(ds);
    return `| [${label}](documents/by-issuer/${local}.md) | ${ds.length} `
      + `| ${range(ds)} | ${shelves} |`;
  });
  const actaBorn = docs.filter((d) => isActaShelf(d.source?.shelf)).length;

  const genreRows = byGenre.map(([genre, ds]) =>
    `| [\`${genre ?? 'unmapped'}\`](documents/by-genre/${genreFile(genre)}.md) `
    + `| ${ds.length} | ${range(ds)} |`);

  const keywordSection = byKeyword.size === 0 ? '' : `
## By keyword

A keyword is a descriptive subject tag and carries no claim about authority.

| Keyword | Documents |
| --- | --- |
${[...byKeyword].sort(([a], [b]) => cmp(a, b)).map(([k, ds]) =>
    `| [\`${k}\`](documents/by-keyword/${k}.md) | ${ds.length} |`).join('\n')}
`;

  const provisionalLine = provisional === 0
    ? `**${docs.length} documents**, none of which carry a provisional identifier.`
    : `**${docs.length} documents**, of which ${provisional} carry a provisional identifier — `
      + 'the source prints no incipit for them, so their id is genre-and-date based and may '
      + 'be re-minted.';

  return `# Magisterial Documents

Generated by \`npm run render\` from \`data/documents/*.json\` — do not edit by hand.

Identifiers follow \`mag:{issuer}/{incipit-slug}-{year}\`, or \`mag:{issuer}/{series-id}-{occasion-year}\`
for a document in an annual series (\`series.id\` and \`series.year\`; the occasion year, not the year it was
signed). The issuer segment is always the local part of \`issuerId\`, so conciliar documents namespace under
their council and record the promulgating pope separately. See the design specs for the minting rules.

${provisionalLine}

Every document appears in both views below; neither is a subset of the other.

## By issuer

| Issuer | Documents | Dates | Shelves harvested |
| --- | --- | --- | --- |
${issuerRows.join('\n')}

## By genre

| Genre | Documents | Dates |
| --- | --- | --- |
${genreRows.join('\n')}
${keywordSection}
## Coverage

This registry covers the **formal document shelves** of vatican.va. Deliberately absent:

- **Occasional acts** — speeches (after Leo XIII, whose are genuine Latin allocutions), homilies,
  general audiences, Angelus addresses, prayers, travels and *cotidie*. They are roughly
  99% of the archive by volume and need an identifier rule for documents whose heading is a bare
  date, which this registry does not yet have.
- **Occasional messages** — the year-partitioned \`pont-messages\` / \`pont_messages\` shelf under
  *Messaggi*, and John Paul I's three messages, which sit directly on his *Messaggi* landing page.
  The annual series sub-shelves (World Day of Peace, Lent, …) and the Urbi et Orbi sub-shelf are
  harvested; the occasional residue is not yet.
- **Year-partitioned \`letters\` shelves** — John XXIII, Benedict XV, and Paul VI onward. The
  \`letters\` shelf is harvested only where the aggregate index carries its items.
- **The shelves are selections, and the *Acta* fill them only where a shelf is harvested.** ${actaBorn === 0
    ? 'No document is yet created from the *Acta Apostolicae Sedis* index.'
    : `${actaBorn} documents are created from the annual *Acta Apostolicae Sedis* index (2015–2024) for acts the
  harvested shelves lack — constitutions, apostolic letters, canonisation decretals; \`source.shelf\` is
  \`aas/{year}\`, the AAS column is their source as well as their citation, and their titles are the index's
  Latin entries.`} An act in a category whose shelf is not harvested (letters, homilies, speeches, occasional
  messages) waits for that harvest; the join report lists every entry held and why.
- **Bishops' conferences and dicasterial documents**, which remain outside the repository's scope.
- **Councils before 1870.** vatican.va's council archive publishes only Vatican I and Vatican II;
  the other nineteen ecumenical councils have no source there, so a registry holding two councils
  is not a registry of the councils.
- ${candidates === 0
    ? '**Circumscription curation is complete.** Every candidate has been adjudicated'
    : `**Circumscription curation is incomplete.** ${candidates} apostolic constitutions still await adjudication`} — each apostolic constitution whose heading
  prints a bare Latin toponym was read against its own text and recorded as an erection, an
  elevation, a union, or an act of another kind named in the adjudication table.

The Shelves harvested column above is generated from the harvest configuration itself, and its AAS
note from the documents, so neither can drift from what was actually read.
`;
}
