import { cell, byDateThenId, idCell, genreCell, FOOTNOTE } from './table.js';
import type { DocumentRecord } from '../types.js';

const GENERATED =
  'Generated by `npm run render` from `data/documents/*.json` — do not edit by hand.';

export function renderIssuerMd(issuerLocal: string, docs: DocumentRecord[]): string {
  const rows = [...docs].sort(byDateThenId);
  const prefix = rows[0]?.issuerId.startsWith('oec:') ? 'oec' : 'rp';
  const head = `# Documents of \`${prefix}:${issuerLocal}\`

${GENERATED}

${rows.length} documents.

| ID | Title | Incipit | Genre | Date | Promulgated by |
| --- | --- | --- | --- | --- | --- |`;

  const body = rows.map((d) =>
    `| ${idCell(d)} | ${cell(d.title)} | ${d.incipit ? cell(d.incipit) : ''} `
    + `| ${genreCell(d)} | ${d.date} | ${d.promulgatedBy ? `\`${d.promulgatedBy}\`` : ''} |`);

  return `${head}\n${body.join('\n')}\n\n${FOOTNOTE}\n`;
}
