import { cell, byDateThenId, idCell, genreCell, FOOTNOTE } from './table.js';
import type { DocumentRecord } from '../types.js';

const GENERATED =
  'Generated by `npm run render` from `data/documents/*.json` — do not edit by hand.';

export function renderKeywordMd(keywordId: string, docs: DocumentRecord[]): string {
  const rows = [...docs].sort(byDateThenId);
  const head = `# Documents keyworded \`${keywordId}\`

${GENERATED}

A keyword is a descriptive subject tag. It makes no claim about the document's authority: see
\`data/keywords.json\` for the term's definition and the design spec §4.5 for how it is applied.

${rows.length} documents.

| ID | Title | Incipit | Genre | Issuer | Date |
| --- | --- | --- | --- | --- | --- |`;

  const body = rows.map((d) =>
    `| ${idCell(d)} | ${cell(d.title)} | ${d.incipit ? cell(d.incipit) : ''} `
    + `| ${genreCell(d)} | \`${d.issuerId}\` | ${d.date} |`);

  return `${head}\n${body.join('\n')}\n\n${FOOTNOTE}\n`;
}
