/**
 * The ASS sample report (ass volumes spec §6-§7, phase 2c-i): for each of the five sample
 * volumes, what the scanner read from the body and the summa said about it, what the join
 * matched and by which rule, what it could not, and the shelf documents of the volume's
 * years with no reference; across the sample, the headings and popes mapped, the readings
 * curated, and the corpus before and after. NEVER run by the harvest: it reads data/ as
 * the harvest wrote it and re-runs the join over the shelf records.
 *
 * A sibling of tools/acta-volumes-report.ts, which reads the AAS sources alone: that tool
 * filters ACTA_SOURCES to `kind !== 'ass'` at module level, so the ASS cannot be an era of
 * it. The prose of §1 is the author's, written against the tables below.
 *
 * Usage: npx tsx tools/ass-volumes-report.ts > docs/superpowers/reports/2026-09-22-ass-volumes-sample.md
 */
import { readFileSync, readdirSync } from 'node:fs';
import { ACTA_SOURCES, applyCuratedReferences, citeRef, loadActaIndexes } from './src/acta/join.js';
import { matchActa, POPE_ISSUERS, type ActaCandidate, type ActaUnmatched } from './src/acta/match.js';
import { createFromActa, isActaShelf } from './src/acta/create.js';
import { categoryForHeading } from './src/acta/categories.js';
import { ACTA_REPRINTS, ACTA_SHARED_PAGES, ASS_READINGS } from './src/acta/curation.js';
import type { AssScan, AssEntry } from './src/acta/ass.js';
import type { DocumentRecord } from './src/types.js';

const allDocs = readdirSync('data/documents').filter((f) => f.endsWith('.json'))
  .flatMap((f) => JSON.parse(readFileSync(`data/documents/${f}`, 'utf8')) as DocumentRecord[])
  .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
const docs = allDocs.filter((d) => !isActaShelf(d.source?.shelf));
const sources = ACTA_SOURCES.filter((s) => s.kind === 'ass');
const { parsed } = loadActaIndexes(sources);
const scans = new Map(sources.map((s) => [s.key, JSON.parse(readFileSync(s.file, 'utf8')) as AssScan]));
const entries = [...parsed.values()].flatMap((p) => p.entries) as AssEntry[];
const result = matchActa(entries, docs);
// ACTA_CURATED_REFERENCES cites an AAS page by type (`series: 'AAS'`), and every row names a
// document this ASS-only run never matches -- a `supersedes` the join did not make is a hard
// error (join.ts). The table passed here is therefore empty: the curated references are the
// AAS report's, and the `curated` column of §3 counts ACTA_MATCH_OVERRIDES, which matchActa
// applies. The call stands so that an ASS row, if one is ever written, lands in the pipeline.
applyCuratedReferences(result, docs, {});
const creation = createFromActa(result, docs);

const out: string[] = [];
const p = (s = '') => out.push(s);
const md = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' / ').replace(/\s+/g, ' ');
/**
 * The date this report was last generated, as `ERA.generatedOn` is in the AAS sibling:
 * bumped by hand when the report is regenerated, so that a re-run is reproducible and the
 * line does not claim the fixtures' scan date, which §1's header prints beside it.
 */
const GENERATED_ON = '2026-09-23';
const cite = (e: AssEntry) => citeRef(e);
const candidateList = (cs: ActaCandidate[]) => cs.map((c) => `\`${c.id}\`${c.incipit ? ` (*${md(c.incipit)}*)` : ''}`).join(', ') || '—';
const of = (k: string) => entries.filter((e) => `ass-${e.volume}` === k);
const pct = (a: number, b: number) => (b === 0 ? '—' : `${((a / b) * 100).toFixed(1)} %`);

p('# The *Acta Sanctae Sedis* sample (ASS 1, 12, 23, 33, 41): the phase-2c-i report');
p();
p(`Generated by \`tools/ass-volumes-report.ts\` on ${GENERATED_ON} from \`data/documents/\`, the entries and summa fixtures in \`tools/fixtures/acta/\` (scanned ${scans.get('ass-41')!.generated}; the retrieval date of each volume is in \`tools/fixtures/acta/README.md\`), and the curated readings (\`ASS_READINGS\`, \`tools/src/acta/curation.ts\`):`);
p('the report of phase 2c-i of [#25](https://github.com/CatholicOS/cmddr/issues/25) as the [ass volumes spec](../specs/2026-09-21-ass-volumes-design.md) §6 defines it.');
p();
// ---------------------------------------------------------------------------------------
// The numbers §1's reading is written against. Every figure the prose states is one of
// these: the prose is written against the tables, and regenerating reproduces it.
// ---------------------------------------------------------------------------------------
/** The scan as the fixture records it, before the readings are applied by the loader. */
const scannedOf = (k: string) => scans.get(k)!.entries.length;
const readOf = (k: string) => of(k).filter((e) => e.anchor === 'reading').length;
const summaOf = (k: string) => scans.get(k)!.summa;
const sum = (f: (k: string) => number) => sources.reduce((n, s) => n + f(s.key), 0);
/** A source's shelf documents of its years with no reference at all: §5's rows. */
const noRef = (s: (typeof sources)[number]) => {
  const issuers = new Set(of(s.key).map((e) => POPE_ISSUERS[e.pope]));
  return docs.filter((d) => issuers.has(d.issuerId) && Number(d.date.slice(0, 4)) >= s.year
    && Number(d.date.slice(0, 4)) <= (s.yearTo ?? s.year) && d.acta === undefined);
};
const defectsBy = (reason: string) => sum((k) => scans.get(k)!.defects.filter((d) => d.reason === reason).length);
/** The no-heading defects quoting the brief's ring formula: the Secretaria Brevium shape. */
const ringDefects = (k: string) => scans.get(k)!.defects.filter((d) => d.reason === 'no-heading' && /nnulo [Pp]iscatoris/.test(d.lines.join(' ')));
/** An unclaimed summa row a curated reading now answers (its page carries a reading). */
const answered = (k: string) => summaOf(k).unclaimed.filter((r) => of(k).some((e) => e.page === r.page && e.anchor === 'reading'));
const readings = Object.entries(ASS_READINGS);
const romanDated = readings.filter(([, r]) => /Kalends|Ides/.test(r.evidence)).length;
const headerRead = readings.filter(([, r]) => /headerAgrees/.test(r.evidence)).length;
const harvested = sum((k) => of(k).filter((e) => (categoryForHeading(e.category)?.harvested ?? 'no') !== 'no').length);
const byRule = (b: string) => result.matches.filter((m) => m.by === b).length;
const um = result.unmatched as (ActaUnmatched & { entry: AssEntry })[];
const umNoCandidate = um.filter((u) => u.sameDate.length === 0);
const umWithCandidate = um.filter((u) => u.sameDate.length > 0);
const umBrevis = umWithCandidate.filter((u) => u.entry.category === 'LITTERAE IN FORMA BREVIS');
/** The entry whose only candidates the join already gave to another entry of the same act. */
/** Finding 9's acts, as the report names them and as the shelf files their one candidate. */
const brevisPages = umBrevis.map((u) => `ASS ${u.entry.volume} p. ${u.entry.page}`).join(', ');
const brevisIds = umBrevis.map((u) => `\`${u.sameDate[0]!.id.replace(/^.*\//, '')}\``).join(', ');
const umClaimedElsewhere = umWithCandidate.filter((u) => u.sameDate.every((c) => result.matches.some((m) => m.documentId === c.id)));
const umClassHold = umWithCandidate.filter((u) => !umBrevis.includes(u) && !umClaimedElsewhere.includes(u));
/** Of the unmatched with no shelf record at all, how many are of class `BREVE` (finding 6). */
const umNoBrevia = umNoCandidate.filter((u) => u.entry.category === 'BREVE').length;
/**
 * `ASS 12 pp. 273, 275; ASS 33 p. 401` — a set of entries listed by volume and page, in
 * volume then page order. The findings that must name *every* member of a computed set
 * enumerate it through this rather than in prose, so that the list cannot fall out of step
 * with the count beside it when a rule moves the numbers under both (phase 2c-ii-a).
 */
const byVolumeAndPage = (es: readonly { volume: number; page: number }[]): string =>
  [...new Set(es.map((e) => e.volume))].sort((x, y) => x - y).map((v) => {
    const ps = es.filter((e) => e.volume === v).map((e) => e.page).sort((x, y) => x - y);
    return `ASS ${v} ${ps.length === 1 ? `p. ${ps[0]}` : `pp. ${ps.join(', ')}`}`;
  }).join('; ');
const standing = entries.filter((e) => e.anchor !== 'reading').length;
const skipped = result.skipped as AssEntry[];
const allocutions = skipped.filter((e) => e.category === 'ALLOCUTIO');
const allocutionsUndated = allocutions.filter((e) => e.date.includes('?'));
const skippedDated = skipped.filter((e) => !e.date.includes('?'));
const skippedAddressed = skippedDated.filter((e) => docs.some((d) => d.issuerId === POPE_ISSUERS[e.pope] && d.date === e.date && d.genre === 'discourse-address'));
const provisional = docs.filter((d) => d.idStatus === 'provisional' && d.date >= '1865-01-01' && d.date <= '1908-12-31');
const provisionalCited = provisional.filter((d) => d.acta !== undefined);
const provisionalWithEntry = provisional.filter((d) => entries.some((e) => e.date === d.date && POPE_ISSUERS[e.pope] === d.issuerId));
const assReprints = Object.entries(ACTA_REPRINTS).filter(([, r]) => r.citationOf.startsWith('ASS:'));
const assShared = Object.keys(ACTA_SHARED_PAGES).filter((k) => k.startsWith('ASS:'));
/**
 * The volumes of the series: vatican.va links one whole-volume PDF per volume, 41 in all
 * (ass volumes spec §1). The years 1865-1908 number 44 because 22 of the 41 labels span
 * two years, so a count of years is not a count of volumes.
 */
const ASS_VOLUMES = 41;
/** The volumes 2c-ii has left: the series, less the five this phase sampled. */
const volumesLeft = ASS_VOLUMES - sources.length;
const gap = (k: string) => noRef(sources.find((s) => s.key === k)!).length;
const eraDocs = docs.filter((d) => d.date >= '1865-01-01' && d.date <= '1908-12-31');
const assCited = allDocs.filter((d) => d.acta?.series === 'ASS');
// Finding 10 names the two readings whose date rests on an emendation of the OCR: matched on
// the phrase each row's evidence states the emendation in, and asserted so the prose cannot
// go stale against the table.
const emended = readings.filter(([, r]) => /\(1950\) is `MDCCCCI`|is the OCR's reading of `III Kalendas`/.test(r.evidence)).map(([k]) => k);
if (emended.length !== 2) throw new Error(`the reading's finding 10 names two emended dates; ${emended.length} ASS_READINGS rows state one`);

p('## 1. Reading');
p();
p(`1. **The body scan works from 1879 on and fails on 1865: the era's headline is a date, not a rule.** Five volumes, one`);
p(`   scanner, and the yield divides at the first of them. ASS 1 (1865–66, ${scans.get('ass-1')!.pages} pages) gave **${scannedOf('ass-1')} acts** — its three`);
p(`   papal acts were read by hand and stand in \`ASS_READINGS\` (§2.5) — while ASS 12 (1879) gave ${scannedOf('ass-12')}, ASS 23 (1890–91) ${scannedOf('ass-23')},`);
p(`   ASS 33 (1900–01) ${scannedOf('ass-33')} and ASS 41 (1908) ${scannedOf('ass-41')} — ${sum(scannedOf)} acts from the five bodies by rule. After the curation the sample`);
p(`   carries **${entries.length} entries, ${standing} of them as the scanner read them** (${pct(standing, entries.length)}) and ${readings.length} read by hand (one reading replacing a`);
p(`   scanned entry, at ASS 41 p. 361, and the rest added where the scan had nothing). The 1865 volume is not a harder instance of the same problem but a different volume: its`);
p(`   class headings are spelt \`LITERAE APOSTOLICAE\` with one T and \`ALLOCVTIO\` with the OCR's V, neither a heading of the`);
p(`   list; its two apostolic letters are printed under \`SECRETARIA BREVIUM\` behind an editor's preface, so the act does not`);
p(`   open where the heading stands; and **its summa has no papal part at all** (${summaOf('ass-1').rows.length} rows, §2) — the pope's acts are listed`);
p(`   under the dicastery that issued them. Scan and check therefore fail together there, which is why the three readings`);
p(`   were admitted under the ruling's last clause and why §2's ASS 1 row is the only one whose every act is curated.`);
p(`   From 1879 the volumes print a class heading, a salutation and a \`Datum Romae\` dateline in the shape the scanner`);
p(`   reads, and the yield rises with the century.`);
p(`2. **The summa is the check, and it checked: the sample's summae list ${sum((k) => summaOf(k).rows.length)} rows, a scanned act opens at ${sum((k) => summaOf(k).claimed.length)} of the pages**`);
p(`   **they cite, ${sum((k) => summaOf(k).unclaimed.length)} rows are left unclaimed, and ${sum((k) => answered(k).length)} of those ${sum((k) => answered(k).length) === 1 ? 'is' : 'are'} answered by a curated reading.** Per volume (§2): ASS 12 claims ${summaOf('ass-12').claimed.length} pages of ${summaOf('ass-12').rows.length} rows and`);
p(`   leaves ${summaOf('ass-12').unclaimed.length} unclaimed; ASS 23, ${summaOf('ass-23').claimed.length} of ${summaOf('ass-23').rows.length}, ${summaOf('ass-23').unclaimed.length}; ASS 33, ${summaOf('ass-33').claimed.length} of ${summaOf('ass-33').rows.length}, ${summaOf('ass-33').unclaimed.length}; ASS 41, ${summaOf('ass-41').claimed.length} of ${summaOf('ass-41').rows.length}, ${summaOf('ass-41').unclaimed.length}. The ${sum((k) => summaOf(k).unclaimed.length) - sum((k) => answered(k).length)} rows that remain unclaimed after the curation (§2.3) are, read one by one, **${sum((k) => summaOf(k).unclaimed.length) - sum((k) => answered(k).length) - 1} rows the papal part`);
p(`   lists that are not a papal act opening at that page** — an address *to* the pope (ASS 12 p. 483), Gregory XVI's`);
p(`   *Inter praecipuas* of 1844 reprinted (12 p. 545), the Secretary of State's own letter (33 p. 715), the *Lex propria*`);
p(`   and the *Ordo servandus* annexed to *Sapienti consilio* (41 pp. 440, 462, 683), the summa's page for *Sapienti*`);
p(`   *consilio* itself (41 p. 427, two pages after its heading at 425), and three dicastery pages (23 pp. 109, 116, 119)`);
p(`   the OCR's interleaving of summa p. 753 turned into papal rows — **and one genuine miss**, ASS 33 p. 193, whose`);
p(`   dateline the OCR broke (the month lifted onto the line above). One miss in ${sum((k) => summaOf(k).rows.length)} rows is the measure of the scan's`);
p(`   completeness where the summa can speak. The other direction is thinner: ${sum((k) => summaOf(k).omitted.length)} scanned acts the summa does not list`);
p(`   (§2.4, which prints every one: ${byVolumeAndPage(sources.flatMap((s) => summaOf(s.key).omitted.map((page) => ({ volume: s.volume, page }))))}). **${sum((k) => summaOf(k).omitted.filter((pg) => of(k).some((e) => e.page === pg && e.category === 'BREVE')).length)} of the ${sum((k) => summaOf(k).omitted.length)} are of class \`BREVE\`**`);
p(`   — the twelve phase 2c-ii-a read from the ring of the Fisherman (ASS 33 pp. 212, 213 and ten of ASS 41, of which`);
p(`   300 and 301 answered a \`header-mismatch\` defect until 2c-ii Task 6's relaxation) and two headed`);
p(`   with the class word and read before it (ASS 12 p. 588, ASS 33 p. 401) — and that is the summa working, not failing:`);
p(`   its papal part *ends* at the dicastery heading \`EX SECRETARIA BREVIUM\`, so a breve printed under that heading is a`);
p(`   papal act the volume's own list was never going to claim, and "omitted" is the check saying so. The other two are`);
p(`   the allocution at ASS 33 p. 396, likewise printed in the dicastery part, and **one artefact**: *Rerum novarum*`);
p(`   (ASS 23 p. 641) is listed by the summa, in the interleaved column of p. 753, where nothing can be read.`);
p(`3. **${sum((k) => scans.get(k)!.defects.length)} defects remain, and the shape they take is one part of the *Acta* the scanner does not enter.** By reason:`);
p(`   ${defectsBy('no-heading')} \`no-heading\`, ${defectsBy('no-date')} \`no-date\`, ${defectsBy('header-mismatch')} \`header-mismatch\`, ${defectsBy('no-opening')} \`no-opening\`, ${defectsBy('unknown-pope')} \`unknown-pope\` (§2.2). **${sum((k) => ringDefects(k).length)} of the ${defectsBy('no-heading')} \`no-heading\` defects quote the brief's ring**`);
p(`   **formula** (\`sub Annulo Piscatoris\`) — ASS 1 ×${ringDefects('ass-1').length}, ASS 12 ×${ringDefects('ass-12').length}, ASS 33 ×${ringDefects('ass-33').length}, ASS 41 ×${ringDefects('ass-41').length} — and they are what is left of the brevia of the`);
p(`   \`EX SECRETARIA BREVIUM\` part, whose heading is a descriptive title rather than a class word and whose summa rows`);
p(`   sit under the dicastery: papal acts by author, invisible to a scanner that anchors on a class heading. Phase 2c-ii-a`);
p(`   gave the walk-back a second reading for them — the pope's own name standing alone under the ring, the title above it`);
p(`   read as the act's description, the class \`BREVE\` — and the sample gained nine acts by it (ASS 33 p. 212; ASS 41`);
p(`   pp. 37, 134, 580, 581, 623, 748, 757, 766), where it had 15 such defects before. What the second reading does not`);
p(`   reach is quoted in §2.2 and none of it is the rule's to fix: three brevia it reads whole but whose running header`);
p(`   the OCR misread, so \`headerAgrees\` refuses them (ASS 33 p. 213 \`215\`, ASS 41 pp. 300 \`3oo\` and 301 \`3oi\`); one`);
p(`   it reads whole and cannot date, ASS 12 p. 636, whose dateline prints no \`die\` (\`sub Annulo piscatoris XIII /`);
p(`   Augusti MDCCCLXXIX\`); the 1896 breve ASS 41 p. 169 quotes inside a later act and the 1900 brief reprinted inside`);
p(`   Pennacchi's commentary at ASS 33 p. 303, neither of which has a title above the pope's name, only body text; and`);
p(`   ASS 1's two apostolic letters, read by hand. Where a defect was a`);
p(`   rule's, the rule went in and was unit-tested; where it was one act's, it became a reading. **The spec's §3 bound is`);
p(`   wrong as written**: it says the walk back from a dateline to its heading is bounded at 40 lines, and \`readAct\``);
p(`   (\`ass.ts\`) bounds it at **the previous anchor** — which is why a \`no-heading\` defect is keyed to the *anchor's*`);
p(`   page and a reading to the page the act opens on (ASS 23 p. 522 answers the defect at 526; ASS 41 p. 555 the defect`);
p(`   at 577).`);
p(`4. **${readings.length} readings carry the sample, and ${romanDated + headerRead} of them are two OCR failures repeating.** ${romanDated} rest on a Roman date the scanner does not`);
p(`   read — the Kalends and the Ides, which the ASS prints where the AAS prints a numeral — and ${headerRead} on a running header`);
p(`   the OCR misread (\`-318\`, \`555\`, \`585\`, \`U9\`, \`2\`/\`98\`, \`5\`/\`49\`), which \`headerAgrees\` refuses. Neither is a`);
p(`   reading of the act: both are the scanner refusing to guess, and each row quotes the lines it was read from (§2.5).`);
p(`   The remaining ${readings.length - romanDated - headerRead} are single acts — ASS 1's three, the Italian-and-Latin letter of ASS 12 p. 3 with neither formula`);
p(`   nor signature, \`MOTU-PRQPRIO\` (23 p. 522), \`rtomae\` (41 p. 195), the French cardinals' list read as an opening`);
p(`   (41 p. 361), the by-line after a blank line (41 p. 555), \`MDCCCCL\` (33 p. 643). **No ASS volume shows a page offset**:`);
p(`   every header-mismatch of the sample is the OCR's reading of the right number, so the PDF page is the printed page in`);
p(`   all five (spec §4's second question, answered yes).`);
p(`5. **${result.matches.length} references written, ${byRule('unique')} by the unique rule and ${byRule('opening')} by the opening rule, with ${result.ambiguous.length} ambiguities and ${result.conflicts.length} conflicts.** Of the ${entries.length} entries,`);
p(`   ${harvested} fall in a category the registry harvests, and **${result.matches.length} of those ${harvested} matched** (${pct(result.matches.length, harvested)}): ASS 1 ${result.matches.filter((m) => m.entry.volume === 1).length}, ASS 12 ${result.matches.filter((m) => m.entry.volume === 12).length}, ASS 23 ${result.matches.filter((m) => m.entry.volume === 23).length},`);
p(`   ASS 33 ${result.matches.filter((m) => m.entry.volume === 33).length}, ASS 41 ${result.matches.filter((m) => m.entry.volume === 41).length} (§3). The rate climbs with the volume and with the shelf behind it, from nothing in 1865 to`);
p(`   ${pct(result.matches.filter((m) => m.entry.volume === 41).length, of('ass-41').filter((e) => (categoryForHeading(e.category)?.harvested ?? 'no') !== 'no').length)} in 1908. **The opening rule is what the ASS needed and the AAS did not.** An ASS entry carries no incipit —`);
p(`   the volumes print no index, so the scanner reads the act's first eight words after the salutation (\`incipit: null\`,`);
p(`   \`opening\`), and the join matches an opening against the shelf's incipit as a prefix. ${byRule('opening')} of the ${result.matches.length} matches rest on it`);
p(`   (§3.1): *Dall'alto dell'Apostolico Seggio* (23 p. 193), *Novum argumentum* (23 p. 318), *Singulari curare* and`);
p(`   *In domibus* (41 pp. 34, 35). The other ${byRule('unique')} are \`unique\` — one shelf record of the pope, the class and the day. No`);
p(`   toponym match, no curated override, and **no ambiguity in the whole sample**: the era's shelf is thin enough that a`);
p(`   pope, a class and a date name one act, where the 2003–2009 indexes produced 60 ambiguities in 1 118 entries (that era's report, §2). The one`);
p(`   page two acts share (ASS 33 p. 641: *De ingenii* of 20 February and *Le nostre ferme speranze* of 28 March 1901) is`);
p(`   curated in \`ACTA_SHARED_PAGES\` (${assShared.length} ASS row), so both are written rather than both withheld by invariant 25.`);
p(`6. **The ${um.length} unmatched divide three ways, and only ${umClassHold.length + umBrevis.length} of them are the join's doing.** ${umNoCandidate.length} have **no shelf record at all on their`);
p(`   date** (§3.3's "Same date" column is empty for every one), and they are ${byVolumeAndPage(umNoCandidate.map((u) => u.entry))}`);
p(`   — ASS 1's two apostolic letters of 1866, three acts of ASS 12 and three of ASS 23 the letters shelf does not hold,`);
p(`   the Lourdes letter of ASS 41 p. 65, and ${umNoBrevia} of class \`BREVE\`: the two the volumes head with the class word`);
p(`   (ASS 12 p. 588, ASS 33 p. 401) and the ${umNoBrevia - 2} phase 2c-ii-a read from the ring, not one of which the briefs shelves`);
p(`   hold. These are the registry's gap, not the scanner's: the act is printed, read, dated and`);
p(`   quoted here, and the shelf has never carried it. ${umBrevis.length} are the \`LITTERAE IN FORMA BREVIS\` of ASS 23 and 33 (finding 9),`);
p(`   ${umClassHold.length} are held by the class rule against an encyclical (finding 7), and ${umClaimedElsewhere.length} is the Latin printing whose one candidate the`);
p(`   Italian printing already claimed (finding 8). Every one of the ${um.length} is held \`series-not-created\` by the creator (§4):`);
p(`   **${creation.created.length} documents were created**, as phase 2c-i intends — the ASS joins, it does not harvest.`);
p(`7. **Two acts of weight are held by the class rule, and both look like override candidates: the owner's call.**`);
p(`   *Catholicae Ecclesiae* of 20 November 1890, on slavery in Africa, is headed \`LITTERAE circulares\` at ASS 23 p. 257`);
p(`   and shelved as an encyclical (\`mag:leo-xiii/catholicae-ecclesiae-1890\`); *Omnibus compertum* of 21 July 1900, to the`);
p(`   Melkites, is headed \`LITTERAE\` at ASS 33 p. 65 and shelved as an encyclical (\`mag:leo-xiii/omnibus-compertum-1900\`).`);
p(`   Each has **exactly one shelf record of its own incipit on its own date**, printed in §3.3's candidate column, and the`);
p(`   join refuses it only because *letter* and *encyclical* are different classes. What the sources show: the ASS heads an`);
p(`   act by what the chancery called the instrument, the shelf files it by what the act is. What I judge, separately:`);
p(`   both are \`ACTA_MATCH_OVERRIDES\` rows waiting to be written, each quoting its heading line — two references gained,`);
p(`   two of the ${um.length} unmatched cleared. **No row was written here.** The decision is editorial, and it decides more than these`);
p(`   two: the ASS calls an encyclical \`EPISTOLA ENCYCLICA\`, \`LITTERAE ENCYCLICAE\`, \`LETTERA ENCICLICA\` and, twice,`);
p(`   plain \`LITTERAE\`, so a ruling here is a ruling for the ${volumesLeft} volumes 2c-ii will scan.`);
p(`8. **One act, two printings, one shelf record: the Latin of *Dall'alto dell'Apostolico Seggio* is held while the Italian**`);
p(`   **is cited — the reverse of the AAS policy.** ASS 23 prints the Italian encyclical at p. 193 (\`LETTERA Enciclica\`)`);
p(`   and its \`(Versio latina)\` at p. 206 (\`LITTERAE Encyclicae\`, *Ab apostolici Solii celsitudine*, the reading`);
p(`   \`ASS:23:206\`). The shelf's incipit is the Italian's, so the opening rule gave p. 193 the document and p. 206 is`);
p(`   unmatched with that same document as its only candidate (§3.3). In the AAS the registry rules the other way —`);
p(`   *Ubi arcano Dei consilio* is cited at its Latin page — and if that policy governs the ASS too, the citation should`);
p(`   move to p. 206 and be carried by a curated reference, not by the opening rule. **Owner's call**; nothing was`);
p(`   changed, and the pages of both printings are quoted in §2.5 and §3.3.`);
p(`9. **The ${umBrevis.length} \`LITTERAE in forma Brevis\` of the sample are a class question, not a matching failure.** ${brevisPages}`);
p(`   are headed \`LITTERAE in forma Brevis\` — ASS 23 p. 437 with the lower-case b that volume prints — which \`categories.ts\` classes \`brief\`; every one has exactly one shelf`);
p(`   record of the same incipit on the same date, and every one of those is on Leo XIII's **letters** shelf as genre \`letter\``);
p(`   (${brevisIds});`);
p(`   none is on a briefs shelf. The candidates are printed in §3.3. Either the class belongs with the letters or the ${umBrevis.length}`);
p(`   shelf records are misfiled — **the owner rules, and the same four words head acts in every volume of the series**.`);
p(`   **One page of the sample is live either way**: ASS 33 p. 3 opens two acts — the Italian letter *I luttuosi avvenimenti* of 16 July 1900,`);
p(`   which is matched, and *Quas Tu* of 8 June 1900, which this finding holds (§2.1, §3.3). Rule the class into the letters and that page`);
p(`   carries **two matched documents**, whereupon invariant 25 withholds *both* references until an \`ACTA_SHARED_PAGES\` row is curated for`);
p(`   \`ASS:33:3\` naming the pair, as \`ASS:33:641\` already is. The ruling is therefore one row of curation wider than it looks.`);
p(`10. **Two of the ${readings.length} readings rest on an emendation of the OCR, and the owner should check them before they are trusted.**`);
p(`   \`${emended[0] ?? 'ASS:33:643'}\`: the dateline prints \`Anno MDCCCCL\`, which is 1950; read as \`MDCCCCI\`, 1901 — the volume's second year, the`);
p(`   twenty-fourth of the pontificate the same line names, and the year of the 450th anniversary the heading names.`);
p(`   \`${emended[1] ?? 'ASS:41:619'}\`: *Promulgandi* is dated \`in Kalendas Octobres\`, which is no Roman date at all; read as \`III Kalendas\`,`);
p(`   29 September 1908 — the same volume reads \`III\` as \`in\` again at p. 298 (\`xxin\` for \`xxiii\`), and AAS 1 p. 6 prints`);
p(`   the same formula as \`III Kalendas Octobres\`. Both emendations are stated in the row's own evidence, and both are`);
p(`   the kind of reading a scanner must never make by rule. **They are the two dates in this report I would want a second`);
p(`   pair of eyes on.**`);
p(`11. **Two acts are printed in both series, and this report cites them at their ASS printing — reversibly, and the owner`);
p(`   should confirm it.** *Sapienti consilio* (ASS 41 (1908) 425; AAS 1 (1909) 7) and *Promulgandi* (ASS 41 (1908) 619;`);
p(`   AAS 1 (1909) 5) were promulgated in the last months of the ASS and reprinted in the first number of the AAS —`);
p(`   *Promulgandi* being the constitution that instituted the AAS, printed on the new gazette's opening page. Both shelf`);
p(`   records already carried an AAS reference (one a curated page of phase 2b-iii-b, one a recovered page), and the join`);
p(`   claimed each twice. \`ACTA_REPRINTS\` has one rule — *the citation of record is the first printing* — so ${assReprints.length} rows were`);
p(`   written, keyed by the later printing (\`${assReprints.map(([k]) => k).join('`, `')}\`) and pointing at the ASS, and the two documents now cite ASS 41. The`);
p(`   two entries of AAS 1 (1909) are now listed as reprints rather than matches in the AAS sample and 1909–1925 era`);
p(`   reports, regenerated with this one, and the corpus counts they print moved with them. **Canonical usage runs the other way** — the *Fontes* and the 1917 Code's apparatus cite both at AAS 1 —`);
p(`   and if the owner prefers that, \`Reprint\` needs a third \`kind\` (a first printing in the superseded series, cited at`);
p(`   its re-issue) and the two rows re-keyed; README's phase 2b-iii-b paragraph and the 1909–1925 era report would then`);
p(`   need the same correction they need today. Nothing here is load-bearing beyond those two rows.`);
p(`12. **The reverse gap is ${sum((k) => gap(k))} documents, and it is Leo XIII's.** The shelf documents of the sample's years carrying no`);
p(`   reference at all (§5): Pius IX ${gap('ass-1')} (1865–66), Leo XIII ${gap('ass-12') + gap('ass-23') + gap('ass-33')} (${gap('ass-12')} in 1879, ${gap('ass-23')} in 1890–91, ${gap('ass-33')} in 1900–01), Pius X ${gap('ass-41')} (1908). Almost`);
p(`   none of them has an ASS entry on its date — §5's last column is empty in all but a handful — so these are acts the`);
p(`   five volumes do not print, not acts the scanner missed: the ASS published the Holy See's acts selectively, and a`);
p(`   volume of ${Math.min(...sources.map((s) => scans.get(s.key)!.pages))}–${Math.max(...sources.map((s) => scans.get(s.key)!.pages))} pages yields between ${Math.min(...sources.map((s) => of(s.key).length))} entries here (ASS 1, all three read by hand) and ${Math.max(...sources.map((s) => of(s.key).length))} (ASS 41). For the era as a whole the registry holds`);
p(`   ${eraDocs.length} shelf documents dated 1865–1908 and **${eraDocs.filter((d) => d.acta).length} of them now carry a reference** (§7) — the five sample volumes' whole`);
p(`   yield. That is the number 2c-ii moves, with ${volumesLeft} volumes left.`);
p(`13. **The allocutions are the one category the sample cannot decide, and the count that would decide it is ${skippedAddressed.length}.** ${skipped.length} entries`);
p(`   are skipped as a category the registry does not harvest (§3.4): ${allocutions.length} allocutions and the chirograph of ASS 33 p. 714.`);
p(`   ${allocutionsUndated.length} of the ${allocutions.length} allocutions carry no date the scanner could read (\`????-??-??\`): the ASS prints an allocution under its`);
p(`   consistorial heading with the date in the heading, not in a dateline, and the scanner reads datelines. Of the`);
p(`   ${skippedDated.length} skipped entries that are dated (two allocutions and the chirograph), **${skippedAddressed.length} has a shelf record of the day on the**`);
p(`   **addresses shelf** — *Multiplices inter*, ASS 1 p. 193,`);
p(`   \`mag:pius-ix/multiplices-inter-1865\`. On that evidence the \`harvested\` flag for \`ALLOCUTIO\` cannot be decided here:`);
p(`   one match in ${skipped.length} is no measurement. 2c-ii should read the allocution's heading for its date first, then count again`);
p(`   over the series' ${ASS_VOLUMES} volumes; the consistorial allocutions of Pius IX and Leo XIII are a shelf of their own, and whether the`);
p(`   registry wants them is a separate question from whether the join can find them.`);
p(`14. **${provisional.length} provisional records sit in the era, and the sample cites ${provisionalCited.length} of them.** §6 lists each with what the ASS prints`);
p(`   at its date: ${provisional.length - provisionalWithEntry.length} have no ASS entry on their date in these five volumes, and one — \`mag:pius-x/letter-1905-06-23\` —`);
p(`   matched ASS 41 p. 19 (*La benevolenza, che nutriamo verso il Pontificio Seminario*, 23 June 1905, printed three`);
p(`   years late, as the ASS often prints) and now carries its reference while keeping its provisional id. A re-mint is`);
p(`   the owner's decision and out of scope; what this report adds is that one of the nine now has a source to be re-minted`);
p(`   from.`);
p(`15. **What 2c-ii should expect.** (a) **The OCR is worst at the start.** ASS 1 (1865) yielded ${scannedOf('ass-1')} acts by rule and needed`);
p(`   ${readOf('ass-1')} hand readings; the volumes of the 1860s and 1870s should be assumed unscannable until measured, and the plan`);
p(`   should budget for reading them rather than for a rule. From 1879 the rate is usable and from 1900 it is good.`);
p(`   (b) **The Secretaria Brevium was the next rule, and it was taken: it is worth 9 acts in these five volumes and 62`);
p(`   across the series.** The brevia print a descriptive title where a class word should stand and are listed by the summa`);
p(`   under the dicastery; reading them means anchoring on the ring formula rather than on a heading, and it moved every`);
p(`   volume's counts. The owner ruled them in on 2026-09-22 and phase 2c-ii-a wrote the rule: the series-wide survey`);
p(`   fell from 105 ring-bearing \`no-heading\` defects to 28 and rose from 380 acts to 442. What 2c-ii should still expect`);
p(`   is that a breve is lost wherever the OCR damages the running header, which finding (d) answers for most of them. (c) **One summa page is unreadable and will be again.** ASS 23's p. 753 is`);
p(`   interleaved word by word by the OCR (two columns with no gutter), so three of its papal rows are lost and three`);
p(`   dicastery pages come out as papal rows; *Rerum novarum* (23 p. 641) therefore reads as "omitted by the summa" in §2.4`);
p(`   although the summa lists it. A re-extraction of that one page, or a hand row, is the cheapest fix, and the shape will`);
p(`   recur wherever the columns touch. (d) **\`header-mismatch\` was relaxed for this series (2c-ii Task 6).** ${defectsBy('header-mismatch')} of the`);
p(`   sample's defects are it now, down from 9: \`headerAgreesASS\` (ass.ts) treats a \`DIGIT_OCR\` letter (summa.ts) as standing for any digit`);
p(`   rather than the one it is keyed to, and, unlike \`headerAgrees\` itself (kept for the AAS page recovery), admits an all-digit token one`);
p(`   edit from the page -- recovering ASS 23 p. 318, ASS 33 pp. 213, 355, 385 and ASS 41 pp. 300, 301 in the sample (three of the six already`);
p(`   answered by a curated reading regardless, so only 213, 300 and 301 are new entries, every one a \`BREVE\` the briefs shelves hold none`);
p(`   of, held \`series-not-created\` like the rule of (b)). Series-wide it fell from 48 to 8 and acts rose by the same 40, to 482; the 8 left`);
p(`   are two edits or worse, or a page number the OCR splits across two lines \`headerOf\`'s single line cannot reach -- none is a run, so`);
p(`   none is a page offset (survey §5).`);
p();
p('## 2. The scan, per volume (spec §3)');
p();
p('| Source | Pages | Summa pages | Scanned by rule | Entries | From a heading | Readings | Defects | Summa rows | Pages claimed | Rows unclaimed | Acts the summa omits |');
p('|---|---|---|---|---|---|---|---|---|---|---|---|');
for (const s of sources) {
  const sc = scans.get(s.key)!;
  const es = of(s.key);
  p(`| ${s.key} (${s.year}${s.yearTo ? `–${s.yearTo}` : ''}) | ${sc.pages} | ${sc.summa.pages ? `${sc.summa.pages.from}–${sc.summa.pages.to}` : '—'} | ${sc.entries.length} | ${es.length} | ${es.filter((e) => e.anchor === 'heading').length} | ${es.filter((e) => e.anchor === 'reading').length} | ${sc.defects.length} | ${sc.summa.rows.length} | ${sc.summa.claimed.length} | ${sc.summa.unclaimed.length} | ${sc.summa.omitted.length} |`);
}
p();
p(`**Reading the columns.** “From a heading” and “Readings” do not sum to “Entries”, and are not meant to: they are two of the three`);
p(`anchors an entry can carry, and the third — the dateline, which the scanner anchors on by rule — is the majority and is not broken`);
p(`out (${entries.filter((e) => e.anchor === 'dateline').length} of the ${entries.length} entries are \`dateline\`, ${entries.filter((e) => e.anchor === 'heading').length} \`heading\`, ${entries.filter((e) => e.anchor === 'reading').length} \`reading\`). “Scanned by rule” is the fixture's own count, taken before the loader applies the`);
p(`readings, so “Entries” is “Scanned by rule” plus “Readings” less the readings that *replace* a scanned entry rather than add one`);
p(`(${sum((k) => scans.get(k)!.entries.length) + readings.length - entries.length} in the sample, at ASS 41 p. 361).`);
p();
p('### 2.1 Acts scanned, with the lines each rests on');
p();
for (const s of sources) {
  p(`<details><summary><b>${s.key}</b> — ${of(s.key).length} acts</summary>`);
  p();
  p('| Page | Category | Pope | Date | Opening | Description | Anchor | Heading (as printed) | Salutation | Dateline (as printed) | Header |');
  p('|---|---|---|---|---|---|---|---|---|---|---|');
  for (const e of of(s.key)) p(`| ${e.page} | ${md(e.category)} | ${e.pope} | ${e.date} | *${md(e.opening)}* | ${md(e.description)} | ${e.anchor} | ${md(e.evidence.heading)} | ${e.evidence.salutation ? md(e.evidence.salutation) : '—'} | ${e.evidence.dateline ? md(e.evidence.dateline) : '—'} | ${md(e.evidence.header)} |`);
  p();
  p('</details>');
  p();
}
p('### 2.2 Scanner defects');
p();
p('| Source | Page | Reason | Lines found |');
p('|---|---|---|---|');
for (const s of sources) for (const d of scans.get(s.key)!.defects) p(`| ${s.key} | ${d.page} | ${d.reason} | ${md(d.lines.join(' / '))} |`);
p();
p('### 2.3 Summa rows unclaimed (the scan opens no act at the page)');
p();
p('| Source | Page | Row (as printed) |');
p('|---|---|---|');
for (const s of sources) for (const r of scans.get(s.key)!.summa.unclaimed) p(`| ${s.key} | ${r.page} | ${md(r.raw)} |`);
p();
p('### 2.4 Acts the summa omits');
p();
p('| Source | Page | Category | Opening |');
p('|---|---|---|---|');
for (const s of sources) for (const pg of scans.get(s.key)!.summa.omitted) { const e = of(s.key).find((x) => x.page === pg); if (e) p(`| ${s.key} | ${pg} | ${md(e.category)} | *${md(e.opening)}* |`); }
p();
p('### 2.5 Curated readings (ASS_READINGS)');
p();
p('| Key | Pope | Category | Date | Opening | Evidence |');
p('|---|---|---|---|---|---|');
for (const [k, r] of Object.entries(ASS_READINGS)) p(`| ${k} | ${r.pope} | ${md(r.category)} | ${r.date} | *${md(r.opening)}* | ${md(r.evidence)} |`);
p();
p('## 3. The join (spec §5)');
p();
p('| Source | Entries | In a harvested category | Matched | unique | opening | toponym | curated | Ambiguous | Unmatched | Skipped (category not harvested) | Claimed twice | Shared pages |');
p('|---|---|---|---|---|---|---|---|---|---|---|---|---|');
for (const s of sources) {
  const es = of(s.key);
  const ms = result.matches.filter((m) => `ass-${m.entry.volume}` === s.key);
  const by = (b: string) => ms.filter((m) => m.by === b).length;
  p(`| ${s.key} | ${es.length} | ${es.filter((e) => (categoryForHeading(e.category)?.harvested ?? 'no') !== 'no').length} | ${ms.length} | ${by('unique')} | ${by('opening')} | ${by('toponym')} | ${by('curated')} | ${result.ambiguous.filter((a) => `ass-${a.entry.volume}` === s.key).length} | ${result.unmatched.filter((u) => `ass-${u.entry.volume}` === s.key).length} | ${result.skipped.filter((e) => `ass-${e.volume}` === s.key).length} | ${result.conflicts.filter((c) => c.entries.some((e) => `ass-${e.volume}` === s.key)).length} | ${result.sharedPages.filter((sp) => sp.matches.some((m) => `ass-${m.entry.volume}` === s.key)).length} |`);
}
p();
p('### 3.1 Matches');
p();
p('| Reference | Category | Date | Opening | Document | By |');
p('|---|---|---|---|---|---|');
for (const m of result.matches) { const e = m.entry as AssEntry; p(`| ${cite(e)} | ${md(e.category)} | ${e.date} | *${md(e.opening)}* | \`${m.documentId}\` | ${m.by} |`); }
p();
p('### 3.2 Ambiguous');
p();
p('| Reference | Category | Date | Opening | Candidates |');
p('|---|---|---|---|---|');
for (const a of result.ambiguous) { const e = a.entry as AssEntry; p(`| ${cite(e)} | ${md(e.category)} | ${e.date} | *${md(e.opening)}* | ${candidateList(a.candidates)} |`); }
p();
p('### 3.3 Unmatched, with what the pope has on the date and a day off');
p();
p('| Reference | Category | Date | Opening | Description | Same date (any class) | Near-misses (±1 day, the class) |');
p('|---|---|---|---|---|---|---|');
for (const u of result.unmatched as (ActaUnmatched & { entry: AssEntry })[]) p(`| ${cite(u.entry)} | ${md(u.entry.category)} | ${u.entry.date} | *${md(u.entry.opening)}* | ${md(u.entry.description)} | ${candidateList(u.sameDate)} | ${candidateList(u.nearMisses)} |`);
p();
p('### 3.4 Skipped: categories the registry does not harvest (the allocutions), with the shelf\'s same-date address');
p();
p('| Reference | Category | Date | Opening | Shelf address on the date |');
p('|---|---|---|---|---|');
for (const e of result.skipped as AssEntry[]) {
  const same = docs.filter((d) => d.issuerId === POPE_ISSUERS[e.pope] && d.date === e.date && d.genre === 'discourse-address').map((d) => `\`${d.id}\``).join(', ') || '—';
  p(`| ${cite(e)} | ${md(e.category)} | ${e.date} | *${md(e.opening)}* | ${same} |`);
}
p();
p('### 3.5 Claimed twice, and shared pages');
p();
for (const c of result.conflicts) p(`- \`${c.documentId}\` claimed by ${c.entries.map((e) => cite(e as AssEntry)).join(' and ')}`);
for (const sp of result.sharedPages) p(`- page ${sp.page} cited by ${sp.matches.map((m) => `\`${m.documentId}\``).join(' and ')} (not curated in ACTA_SHARED_PAGES; neither written)`);
p();
p('## 4. Held by the creator');
p();
const byReason = new Map<string, number>();
for (const h of creation.held) byReason.set(h.reason, (byReason.get(h.reason) ?? 0) + 1);
p('| Reason | Entries |'); p('|---|---|');
for (const [r, n] of [...byReason].sort()) p(`| ${r} | ${n} |`);
p(); p(`Created: ${creation.created.length} (expected 0: phase 2c-i joins only).`); p();
p('## 5. Shelf documents of the volume years with no reference (the reverse gap)');
p();
for (const s of sources) {
  const ds = noRef(s);
  p(`<details><summary><b>${s.key}</b> — ${ds.length} documents dated ${s.year}${s.yearTo ? `–${s.yearTo}` : ''} with no reference</summary>`);
  p(); p('| Document | Date | Class | Incipit | ASS entries on this date |'); p('|---|---|---|---|---|');
  for (const d of ds) {
    const same = of(s.key).filter((e) => e.date === d.date && POPE_ISSUERS[e.pope] === d.issuerId).map((e) => `${cite(e)} ${md(e.category)} *${md(e.opening)}*`).join('; ') || '—';
    p(`| \`${d.id}\` | ${d.date} | ${d.genre} | ${d.incipit ? `*${md(d.incipit)}*` : '—'} | ${same} |`);
  }
  p(); p('</details>'); p();
}
p('## 6. The provisional records of the era, with what the ASS prints at their date');
p();
p('| Document | Date | Class | ASS entries on this date |'); p('|---|---|---|---|');
for (const d of docs.filter((d) => d.idStatus === 'provisional' && d.date >= '1865-01-01' && d.date <= '1908-12-31')) {
  const same = entries.filter((e) => e.date === d.date && POPE_ISSUERS[e.pope] === d.issuerId).map((e) => `${cite(e)} ${md(e.category)} *${md(e.opening)}*`).join('; ') || '—';
  p(`| \`${d.id}\` | ${d.date} | ${d.genre} | ${same} |`);
}
p();
p('## 7. Corpus');
p();
p(`Documents: ${allDocs.length}; with an ASS reference: ${assCited.length}; shelf documents dated 1865–1908: ${eraDocs.length}, of which with a reference of either series: ${eraDocs.filter((d) => d.acta).length}.`);
process.stdout.write(out.join('\n') + '\n');
